DROP TABLE IF EXISTS em_situation_projection;
DROP TABLE IF EXISTS em_external_call_log;
DROP TABLE IF EXISTS em_control_command;
DROP TABLE IF EXISTS em_video_reference;
DROP TABLE IF EXISTS em_external_alert;
DROP TABLE IF EXISTS em_verification_config;
DROP TABLE IF EXISTS em_knowledge_item;
DROP TABLE IF EXISTS em_attendance_alert;
DROP TABLE IF EXISTS em_attendance_record;
DROP TABLE IF EXISTS em_check_point;
DROP TABLE IF EXISTS em_duty_schedule;
DROP TABLE IF EXISTS em_evaluation_template;
DROP TABLE IF EXISTS em_drill_execution;
DROP TABLE IF EXISTS em_drill_plan;
DROP TABLE IF EXISTS em_inventory_plan;
DROP TABLE IF EXISTS em_stock_ledger;
DROP TABLE IF EXISTS em_material_site;
DROP TABLE IF EXISTS em_position_snapshot;
DROP TABLE IF EXISTS em_emergency_group;
DROP TABLE IF EXISTS em_person_ref;
DROP TABLE IF EXISTS em_incident_update;
DROP TABLE IF EXISTS em_incident_type;
ALTER TABLE em_plan_version DROP COLUMN IF EXISTS updated_at;
ALTER TABLE em_plan_version DROP COLUMN IF EXISTS payload;
DROP TABLE IF EXISTS em_plan;
DROP TABLE IF EXISTS em_plan_type;
