<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import AsyncState from '@/components/AsyncState.vue'
import AttachmentRefsField from '@/components/AttachmentRefsField.vue'
import PlatformAttachmentField from '@/components/PlatformAttachmentField.vue'
import { createResponseWorkflow, visibleError, type VisibleError, type WorkflowItem } from '@/features/response/workflow'
import { useAuthContext } from '@/shared/auth/auth-context'
import { useApiClient } from '@/shared/http/api-context'

defineProps<{ audience: 'web' | 'h5' }>()
const auth = useAuthContext(), workflow = createResponseWorkflow(useApiClient())
const tasks = ref<WorkflowItem[]>([]), loading = ref(true), error = ref<VisibleError | null>(null), busy = ref(''), notice = ref('')
const feedback = reactive({ content: '', progressPercent: 0, attachmentFileIds: [] as string[] })
const temporary = reactive({ name: '', assigneeRef: '', deadlineAt: '', description: '' })
const temporaryOpen = ref(false)
const can = (permission: string) => auth.hasAnyPermission([permission])
async function load() { loading.value = true; error.value = null; try { tasks.value = await workflow.listTasks() } catch (cause) { error.value = visibleError(cause) } finally { loading.value = false } }
async function run(key: string, operation: () => Promise<unknown>, message: string) { busy.value = key; error.value = null; notice.value = ''; try { await operation(); notice.value = message; await load() } catch (cause) { error.value = visibleError(cause) } finally { busy.value = '' } }
onMounted(load)
</script>
<template><section class="flow-page"><header class="flow-heading"><div><span class="eyebrow">G2-FR-015 / 022 · 正式 API</span><h2>任务接收与反馈</h2><p>任务确认、进度和附件反馈均保留服务端状态与资源版本。</p></div><button v-if="audience === 'web' && can('task:create')" class="primary" @click="temporaryOpen = !temporaryOpen">临时任务</button></header><form v-if="temporaryOpen" class="action-form" @submit.prevent="run('temporary', () => workflow.createTemporaryTask({ ...temporary, deadlineAt: new Date(temporary.deadlineAt).toISOString() }), '临时任务已创建。')"><div class="form-grid"><label>任务名称<input v-model.trim="temporary.name" required/></label><label>执行人<input v-model.trim="temporary.assigneeRef" required/></label><label>截止时间<input v-model="temporary.deadlineAt" type="datetime-local" required/></label><label>说明<input v-model.trim="temporary.description"/></label></div><button class="primary" :disabled="busy === 'temporary'">创建临时任务</button></form><p v-if="notice" class="notice">{{ notice }}</p><AsyncState v-if="loading" state="loading" message="正在加载授权范围内任务。"/><AsyncState v-else-if="error" :state="error.kind" :message="error.message" :trace-id="error.traceId" @retry="load"/><AsyncState v-else-if="tasks.length === 0" state="empty"/><div v-else class="record-grid"><article v-for="task in tasks" :key="task.id" class="record-card"><header><div><h3>{{ task.title }}</h3><small>{{ task.id }}</small></div><span class="status-chip">{{ task.status }}</span></header><dl><div><dt>执行人</dt><dd>{{ task.assignee || '待分派' }}</dd></div><div><dt>截止时间</dt><dd>{{ task.deadlineAt || '—' }}</dd></div><div><dt>当前进度</dt><dd>{{ task.progressPercent }}%</dd></div></dl><div class="card-actions"><button :disabled="!can('task:acknowledge') || busy === `ack-${task.id}`" @click="run(`ack-${task.id}`, () => workflow.acknowledgeTask(task), '任务接收请求已提交。')">{{ can('task:acknowledge') ? '接收任务' : '无接收权限' }}</button><button :disabled="!can('task:remind')" @click="run(`remind-${task.id}`, () => workflow.remindTask(task, '请尽快反馈进展'), '催办请求已提交。')">{{ can('task:remind') ? '催办' : '无催办权限' }}</button><button :disabled="!can('task:complete')" @click="run(`complete-${task.id}`, () => workflow.completeTask(task, '处置完成'), '任务完成请求已提交。')">{{ can('task:complete') ? '完成任务' : '无完成权限' }}</button></div><details><summary>提交反馈</summary><div class="inline-actions"><label>反馈内容<textarea v-model.trim="feedback.content" required rows="2"/></label><label>进度（0–100）<input v-model.number="feedback.progressPercent" type="number" min="0" max="100"/></label><PlatformAttachmentField v-if="audience === 'h5'" v-model="feedback.attachmentFileIds" capture/><AttachmentRefsField v-else v-model="feedback.attachmentFileIds"/><button :disabled="!can('task:feedback') || !feedback.content || busy === `feedback-${task.id}`" @click="run(`feedback-${task.id}`, () => workflow.feedbackTask(task, feedback), '任务反馈已提交。')">{{ can('task:feedback') ? '提交反馈' : '无反馈权限' }}</button></div></details></article></div></section></template>
